export NPROCS=8

echo This job has allocated $NPROCS nodes


echo  command to EXE:
PROGRAM="./sceptic3Dmpi -d1. -s200 -nr200 -nt10 -np2 --sp -f -g --mcrnt30 --mcrnp30 --subcyc
-x100. -l20. -kt1 -k1e-10 -t0.01 -pf --bcr3"
echo mpirun -l -np $NPROCS $PROGRAM
echo
mpirun -l -np $NPROCS $PROGRAM

echo  command to EXE:
PROGRAM="./sceptic3Dmpi -d1. -s200 -nr200 -nt10 -np2 --sp -f -g --mcrnt30 --mcrnp30 --subcyc
-x100. -l20. -t0.01 -pf --bcr3"
echo mpirun -l -np $NPROCS $PROGRAM
echo
mpirun -l -np $NPROCS $PROGRAM



sleep 1
exit


