#!/bin/bash
# Script to choose (return) compiler version for specified language (f77, f90, etc.)

case $1 in
     f77)

if [ "`which mpif77`" ] ; then
   # By default use mpif77
   COMPILER=mpif77
   if [$2 -eq "nonmpi"] ; then
      # If non-mpi requested, figure out which compiler mpi uses
      if [ "`mpif77 -show`" } ; then
         COMPILER=`mpif77 -show | awk '{ print $$1}'`
      fi
   fi
elif [ "`which gfortran`" ] ; then
   # Else use gfortran
   COMPILER=gfortran
elif [ "`which g77`" ] ; then
   # Else use g77
   COMPILER=g77
else
   # Or whatever was specified
   COMPILER=$G77
fi

     ;;
     f90)

if [ "`which mpif90`" ] ; then
   # By default use mpif90
   COMPILER=mpif90
elif [ "`which gfortran`" ] ; then
   # Else use gfortran
   COMPILER=gfortran
else
   # Or whatever was specified
   COMPILER=$G90
fi

     ;;
esac  



# Return compiler choice
echo $COMPILER